name: Deploy to Production Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /var/www/ai-platform
          
          # Останавливаем сервис
          pm2 stop ai-platform || true
          
          # Обновляем код (если есть Git репозиторий)
          # git pull origin main || true
          
          # Устанавливаем зависимости
          npm ci --legacy-peer-deps
          
          # Запускаем сервис
          pm2 start server.js --name ai-platform --env production
          pm2 save
          
          echo "✅ Автоматический деплой завершен!"